name: CI for Multiple Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["Image reconstruction", "Game of life"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test in Dev Container
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          runCmd: |
            set -e
            cd "${{ matrix.project }}"
            cmake -B build -S .
            cmake --build build
            ctest --test-dir build --output-on-failure
