name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libopenmpi-dev libomp-dev catch2
    - name: Configure CMake
      run: |
        cd "Game of life"
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: |
        cd "Game of life/build"
        make
    - name: Test
      run: |
        cd "Game of life/build"
        ctest
